name: Deploy Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build backend (if needed)
        run: npm run build || echo "No build script"

      # Create Firebase Service Account from secret
      - name: Create Firebase Service Account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > ./src/config/serviceAccountKey.json

      # Install Railway CLI
      - name: Install Railway CLI
        run: curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh

      # Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          FIREBASE_SERVICE_ACCOUNT_PATH: ./src/config/serviceAccountKey.json
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          FEED_CACHE_KEY: feed:recent
          FEED_CACHE_TTL: 10
        run: |
          # Deploy directly without linking
          railway up --detach
